apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-world
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
---
apiVersion:
kind:
metadata:
  name: hello-world-taskrun
spec:
  taskRef:
    name: hello-world
  trigger:
    type: manual